items/urls.py
from django.urls import path
from . import views
from .views import export_to_csv, accountant_export_to_csv

app_name = 'items'

urlpatterns = [
    path('', views.ItemListView.as_view(), name='list'),
    path('create/', views.ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('export', export_to_csv, name='export'),
    path('acc_export/<int:church_id>', accountant_export_to_csv, name='acc_export'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse


def home(request):
    return HttpResponse("You are logged in!")

def accountant_view(request):
    return HttpResponse("This is the page for the accountant. You are logged in")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("home/", home, name="home"),
    path("items/", include('items.urls')),
    path("churches/", include('churches.urls')),

]

items/models.py
from django.db import models
from datetime import date
# Create your models here.

class Item(models.Model):
    CHOICES = [
        ('Neprecizat', 'Neprecizat'),
        ('Comision', 'Comision'),
        ('Consumabile', 'Consumabile'),
        ('Contribuții oficiale', 'Contribuții oficiale'),
        ('Cult', 'Cult'),
        ('Cutia Milei', 'Cutia Milei'),
        ('Deplasări', 'Deplasări'),
        ('Depuneri', 'Depuneri numerar'),
        ('Dobândă', 'Dobândă'),
        ('Donație', 'Donație'),
    ]
    CHOICES2 = [
        ('Încasare', 'Încasare'),
        ('Plată','Plată'),
    ]
    CHOICES3 = [
        ('Numerar', 'Numerar'),
        ('Card', 'Card'),
    ]
    data = models.DateField(default=date.today())
    document = models.IntegerField(default=1)
    denumire = models.CharField(max_length=200, blank = True)
    adresa = models.CharField(max_length=100, blank = True)
    explicatii = models.CharField(max_length=1000, blank = True)
    felul = models.CharField(max_length=100, choices=CHOICES, default='Neprecizat')
    tip = models.CharField(max_length=100, choices=CHOICES2, default='Încasare', blank = False)
    tip_incasare = models.CharField(max_length=100, choices=CHOICES3, default='Numerar', blank = False)
    pret = models.FloatField(default=0)
    church = models.ForeignKey('churches.Church', on_delete=models.CASCADE,related_name='items', blank=False, default=1)

    def __str__(self):
        return self.denumire

items/views.py
from urllib import request
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Item
from django.shortcuts import render, get_object_or_404
from django.views import View
import csv
from churches.models import Church
from django.db import models

class ItemListView(LoginRequiredMixin, View):
    def get(self,request):
        user = self.request.user
        it = Item.objects.filter(church=user.assigned_church)
        cautare = request.GET.get('cautare', '')
        if cautare:
            it=it.filter(models.Q(explicatii__icontains=cautare))
        running_balance = 0
        items = []
        for item in it:
            if item.tip == 'Încasare':
                running_balance += item.pret
            elif item.tip == 'Plată':
                running_balance -= item.pret
            item.current_balance = running_balance
            items.append(item)

        ctx = {'church': user.assigned_church, 'item_list': items}
        return render(request, 'items/item_list.html', ctx)

class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    fields = ['data', 'document', 'denumire', 'adresa', 'explicatii', 'felul', 'tip', 'tip_incasare', 'pret']
    template_name = "items/item_form.html"
    success_url = reverse_lazy("items:list")

    def form_valid(self, form):
        form.instance.church = self.request.user.assigned_church
        return super().form_valid(form)

class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['data', 'document', 'denumire', 'adresa', 'explicatii', 'felul', 'tip', 'tip_incasare', 'pret']
    template_name = "items/item_form.html"
    success_url = reverse_lazy("items:list")
    def get_queryset(self):
        return Item.objects.all(church=self.request.user.assigned_church)

class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = "items/item_delete.html"
    success_url = reverse_lazy("items:list")
    def get_queryset(self):
        return Item.objects.all(church=self.request.user.assigned_church)

def export_to_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Executie bugetara.csv"'
    writer = csv.writer(response)
    writer.writerow([
        'Data',
        'Document',
        'Denumire',
        'Adresa',
        'Explicatii',
        'Felul',
        'Tipul platii',
        'Modul platii',
        'Valoare',
        'Sold'
    ])
    user = request.user
    year = request.GET.get('year')
    items=Item.objects.filter(church=user.assigned_church)
    year = int(year) if year else None
    items=items.filter(data__year=year)
    running_balance = 0
    items_list = []
    for item in items:
        if item.tip == 'Încasare':
            running_balance += item.pret
        elif item.tip == 'Plată':
            running_balance -= item.pret
        item.current_balance = running_balance
        items_list.append(item)

    for item in items_list:
        writer.writerow([
            item.data,
            item.document,
            item.denumire,
            item.adresa,
            item.explicatii,
            item.felul,
            item.tip,
            item.tip_incasare,
            item.pret,
            item.current_balance
        ])

    return response

def accountant_export_to_csv(request, church_id):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="Executie bugetara.csv"'
    writer = csv.writer(response)
    writer.writerow([
        'Data',
        'Document',
        'Denumire',
        'Adresa',
        'Explicatii',
        'Felul',
        'Tipul platii',
        'Modul platii',
        'Valoare',
        'Sold'
    ])
    church = get_object_or_404(Church, id=church_id)
    items = Item.objects.filter(church=church)
    year = request.GET.get('year')
    year = int(year) if year else None
    items=items.filter(data__year=year)
    running_balance = 0
    items_list = []
    for item in items:
        if item.tip == 'Încasare':
            running_balance += item.pret
        elif item.tip == 'Plată':
            running_balance -= item.pret
        item.current_balance = running_balance
        items_list.append(item)

    for item in items_list:
        writer.writerow([
            item.data,
            item.document,
            item.denumire,
            item.adresa,
            item.explicatii,
            item.felul,
            item.tip,
            item.tip_incasare,
            item.pret,
            item.current_balance
        ])

    return response

items/templates/items/item_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ștergere Item</title>
</head>
<body>
<h2>Ștergere item</h2>
<form method="post">
        {% csrf_token %}
        <p>Sunteți sigur că doriți să ștergeți acest item?</p>
        <button type="submit">Șterge</button>
        <a href="{% url 'items:list' %}">Anulare</a>
    </form>

</body>
</html>

items/templates/items/item_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if form.instance.pk %}Editare Item{% else %}Adăugare Item Nou{% endif %}</title>
</head>
<body>
    <h2>
        {% if form.instance.pk %}
            Editare Item
        {% else %}
            Adăugare Item Nou
        {% endif %}
    </h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            {% if form.instance.pk %}Salvare{% else %}Adăugare Item{% endif %}
        </button>
    </form>

    <p><a href="{% url 'items:list' %}">Înapoi</a></p>
</body>
</html>

items/templates/items/item_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listă</title>
</head>
<body>
    <h2>{{ church.name }}</h2>
    <form method="get" action="{% url 'items:export' %}">
        <label for="year">Alegeți anul:</label>
        <input type="number" id="year" name="year" value="{{ request.GET.year }}" placeholder="2025" min="2025" max="2100">
        <button type="submit">Exportă Execuția Bugetară</button>

    </form>
    <p>
        <a href="{% url 'items:create' %}">Adăugare item nou</a>
    </p>

     <form method="get" action="{% url 'items:list' %}">
         <input type="text" name="cautare" placeholder="Căutare" value="{{ request.GET.cautare }}">
         <button type="submit">Caută</button>
     </form>

    <table border="1">
        <tr>
            <th>Data</th>
            <th>Document</th>
            <th>Denumire</th>
            <th>Adresa</th>
            <th>Explicații</th>
            <th>Felul</th>
            <th>Tipul plății</th>
            <th>Modul plății</th>
            <th>Valoare</th>
            <th>Actiuni</th>
            <th>SOLD dupa tranzacție</th>
        </tr>

        {% for item in item_list %}
        <tr>
            <td>{{ item.data }}</td>
            <td>{{ item.document }}</td>
            <td>{{ item.denumire }}</td>
            <td>{{ item.adresa }}</td>
            <td>{{ item.explicatii }}</td>
            <td>{{ item.felul }}</td>
            <td>{{ item.tip }}</td>
            <td>{{ item.tip_incasare }}</td>
            <td>{{ item.pret }}</td>
            <td>
                <a href="{% url 'items:update' item.pk %}">Editare</a> |
                <a href="{% url 'items:delete' item.pk %}">Ștergere</a>
            </td>
            <td>{{ item.current_balance }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">Nu există încă informații</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

items/templates/items/item_list_only.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista</title>
</head>
<body>
    <h1>{{ church.name }}</h1>
    <form method="get" action="{% url 'items:acc_export' church.id%}">
        <label for="year">Alegeți anul:</label>
        <input type="number" id="year" name="year" value="{{ request.GET.year }}" placeholder="2025" min="2020" max="2100">
        <button type="submit">Exportă Execuția Bugetară</button>
    </form>
    <table border="1">
        <tr>
            <th>Data</th>
            <th>Document</th>
            <th>Denumire</th>
            <th>Adresa</th>
            <th>Explicații</th>
            <th>Felul</th>
            <th>Tipul plății</th>
            <th>Modul plății</th>
            <th>Valoare</th>
            <th>SOLD dupa tranzacție</th>
        </tr>

        {% for item in item_list %}
        <tr>
            <td>{{ item.data }}</td>
            <td>{{ item.document }}</td>
            <td>{{ item.denumire }}</td>
            <td>{{ item.adresa }}</td>
            <td>{{ item.explicatii }}</td>
            <td>{{ item.felul }}</td>
            <td>{{ item.tip }}</td>
            <td>{{ item.tip_incasare }}</td>
            <td>{{ item.pret }}</td>
            <td>{{ item.current_balance }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7">Nu există încă informații</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>