accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path("password_reset/",
         auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
         name="password_reset"),

    path("password_reset/done/",
         auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),
         name="password_reset_done"),

    path("reset/<uidb64>/<token>/",
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),
         name="password_reset_confirm"),

    path("reset/done/",
         auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name="password_reset_complete"),
    path('', views.home_view, name='home'),
]

items/urls.py
from django.urls import path
from . import views
from .views import export_to_csv, accountant_export_to_csv

app_name = 'items'

urlpatterns = [
    path('', views.ItemListView.as_view(), name='list'),
    path('create/', views.ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete'),
    path('export', export_to_csv, name='export'),
    path('acc_export/<int:church_id>', accountant_export_to_csv, name='acc_export'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse


def home(request):
    return HttpResponse("You are logged in!")

def accountant_view(request):
    return HttpResponse("This is the page for the accountant. You are logged in")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("home/", home, name="home"),
    path("items/", include('items.urls')),
    path("churches/", include('churches.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    ROLE_CHOICES = [
        ('USER', 'User'),
        ('CONTABIL', 'Contabil'),
        ('ADMIN', 'Admin'),
        ('ARHIEPISCOP', 'Arhiepiscop'),
    ]
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='USER')
    full_name = models.CharField(max_length=255)
    assigned_church = models.ForeignKey('churches.Church', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.username} ({self.role})"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login,  logout
from django.contrib.auth.models import User
from django.contrib import messages

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.role == 'USER':
                return redirect('/items/')
            elif user.role == 'CONTABIL':
                return redirect('/churches/')
            elif user.role == 'ADMIN':
                return redirect('home')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'accounts/login.html')

def home_view(request):
    return render(request, 'accounts/home_page.html')

def logout_view(request):
    logout(request)
    return redirect('login')

accounts/templates/accounts/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Acasă</title>
</head>
<body>
<h1>Acasă</h1>

{% if request.user.is_authenticated %}
    <p>Sunteti autentificat {{ request.user.username}}!</p>
    {% if request.user.role != 'CONTABIL' %}
        <a href="{% url 'items:list' %}"><button type="button">Lista</button></a>
    {% endif %}
    <a href="{% url 'logout' %}"><button type="button">Logout</button></a>
    {%  else %}
        <a href="{% url 'login' %}"><button type="button">Login</button></a>
{%  endif %}

</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login page</title>
</head>
<body>
<h1>Login</h1>
{% if messages %}
      {% for message in messages %}
                <p>{{ message }}</p>
      {% endfor %}
{% endif %}
<form method="POST">
    {% csrf_token %}
        <label>Username:</label>
        <input type="text" name="username" required><br><br>
        <label>Parola:</label>
        <input type="password" name="password" required><br>
        <a href="{% url 'password_reset' %}">Am uitat parola</a><br><br>
        <button type="submit">Login</button>
</form>
</body>
</html>

accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resetare parola</title>
</head>
<body>
<p>Introduceti email-ul aferent contului dumneavoastra, pentru a schimba parola</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Trimite email de resetare</button>
</form>
</body>
</html>

accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parola resetata</title>
</head>
<body>
<h1>Parola a fost resetata pentru contul dumneavoastra</h1>
<a href="{% url 'login' %}">Login</a>
</body>
</html>

accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Setare parola noua</title>
</head>
<body>
<h1>Setare parola noua</h1>
<form method="post">
    {%  csrf_token %}
    {{ form.as_p }}
    <button type="submit">Resetati parola</button>
</form>
</body>
</html>

accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email trimis</title>
</head>
<body>
<p>Daca email-ul introdus este inregistrat email-ul de resetare a fost trimis.</p>
<p>Daca nu aveti un cont cu email-ul introdus, nu veti primi email-ul de resetare</p>
<a href={%  url 'login' %}>Inapoi la fereastra de login</a>
</body>
</html>